advert/urls.py
from django.urls import include, path
from django.contrib import admin

from . import views

urlpatterns = [
    path('', views.AdvertListView.as_view(), name='advert_changelist'),
    path('add/', views.AdvertCreateView.as_view(), name='advert_add'),
    path('<int:pk>/', views.AdvertUpdateView.as_view(), name='advert_change'),
    path('ajax/load-models/', views.load_models, name='ajax_load_models'),
]

car_sales/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='advert_changelist'), name='home'),
    path('admin/', admin.site.urls),
    path('advert/', include('advert.urls')),
]

advert/models.py
from django.db import models


class CarBrand(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class CarModel(models.Model):
    brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Advert(models.Model):
    brand = models.ForeignKey(CarBrand, on_delete=models.SET_NULL, null=True)
    model = models.ForeignKey(CarModel, on_delete=models.SET_NULL, null=True)
    category = models.IntegerField()
    price = models.IntegerField()
    name = models.CharField(max_length = 50)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=100)
    birthdate = models.DateField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

advert/forms.py
from django import forms
from .models import Advert, CarModel

class AdvertForm(forms.ModelForm):
    class Meta:
        model = Advert
        fields = ('brand', 'model', 'category', 'price', 'name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['model'].queryset = CarModel.objects.none()

        if 'brand' in self.data:
            try:
                brand_id = int(self.data.get('brand'))
                self.fields['model'].queryset = CarModel.objects.filter(brand_id=brand_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the advert; ignore and fallback to empty CarModel queryset
        elif self.instance.pk:
            self.fields['model'].queryset = self.instance.brand.carmodel_set.order_by('name')

advert/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy

from .models import Advert, CarModel
from .forms import AdvertForm


class AdvertListView(ListView):
    model = Advert
    context_object_name = 'adverts'


class AdvertCreateView(CreateView):
    model = Advert
    form_class = AdvertForm
    success_url = reverse_lazy('advert_changelist')


class AdvertUpdateView(UpdateView):
    model = Advert
    form_class = AdvertForm
    success_url = reverse_lazy('advert_changelist')


def load_models(request):
    brand_id = request.GET.get('brand')
    models = CarModel.objects.filter(brand_id=brand_id).order_by('name')
    return render(request, 'advert/model_dropdown_list_options.html', {'models': models})

advert/templates/advert/advert_form.html
{% extends 'wrapper.html' %}

{% block content %}

  <h2>Advert Form</h2>

  <form method="post" id="advertForm" data-models-url="{% url 'ajax_load_models' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Зберегти</button>
    <a href="{% url 'advert_changelist' %}">Відмінити</a>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_brand").change(function () {
      var url = $("#advertForm").attr("data-models-url");
      var brandId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'brand': brandId
        },
        success: function (data) {
          $("#id_model").html(data);
        }
      });
    });
  </script>

{% endblock %}

advert/templates/advert/advert_list.html
{% extends 'wrapper.html' %}
{% load static %}

{% block title %}Car Sales List{% endblock %}

{% block content %}
{% csrf_token %}
  <table id="table" data-toggle="table" data-filter-control="true" data-toolbar="#toolbar" class="table-responsive">
    <thead>
      <tr>
        <th data-field="id" data-sortable="true">Id</th>
        <th data-field="brand" data-filter-control="select" data-sortable="true">Марка</th>
        <th data-field="model" data-filter-control="select" data-sortable="true">Модель</th>
        <th data-field="category" data-filter-control="select" data-sortable="true">Категорія</th>
        <th data-field="price" data-sortable="true">Ціна, $</th>
      </tr>
    </thead>
    <tbody>
      {% for advert in adverts %}
        <tr class='clickable-row' data-href="{% url 'advert_change' advert.pk %}">
          <td>{{ advert.pk }}</td>
          <td>{{ advert.brand.name }}</td>
          <td>{{ advert.model.name }}</td>
          <td>
            {% if advert.category < 1990 %}
                До 1990 року випуску
            {% elif advert.category < 2000 %}
                Від 1990 до 2000 року випуску
            {% else %}
                {% if advert.category < 2010 %}
                    Від 2000 до 2010 року випуску
                {% else %}
                    Після 2010 року випуску
                {% endif %}
            {% endif %}
          </td>
          <td>{{ advert.price }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">Немає оголошень в базі. <a href="{% url 'advert_add' %}">Додати перше оголошення</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.0/bootstrap-table.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.9.1/extensions/editable/bootstrap-table-editable.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.9.1/extensions/export/bootstrap-table-export.js"></script>
  <script src="https://rawgit.com/hhurz/tableExport.jquery.plugin/master/tableExport.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.9.1/extensions/filter-control/bootstrap-table-filter-control.js"></script>

  <script>
    var $table = $('#table');
    $(function () {
        $('#toolbar').find('select').change(function () {
            $table.bootstrapTable('refreshOptions', {
                exportDataType: $(this).val()
            });
        });
    })

		var trBoldBlue = $("table");

  	$(trBoldBlue).on("click", "tr", function (){
  			$(this).toggleClass("bold-blue");
  	});
  </script>

  <script>
    jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
            window.location = $(this).data("href");
        });
    });
  </script>
{% endblock %}

advert/templates/advert/model_dropdown_list_options.html
<option value="">---</option>
{% for model in models %}
<option value="{{ model.pk }}">{{ model.name }}</option>
{% endfor %}

templates/wrapper.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Car Sales{% endblock %}</title>

  <!-- favicon -->
  <link href="{% static "img/icon.png" %}" rel=icon>

  <!-- web-fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500" rel='stylesheet' type='text/css'>

  <!-- Bootstrap -->
  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "css/bootstrap-editable.css" %}" rel="stylesheet">
  <link href="{% static "css/bootstrap-table.min.css" %}" rel="stylesheet">

  <!-- font-awesome -->
  <link href="{% static "fonts/font-awesome/font-awesome.min.css" %}" rel="stylesheet">

  <!-- Theme Style -->
  <link href="{% static "css/style.css" %}" rel="stylesheet">
</head>
<body>
  <div class="content-wrapper">
    <section id="header_section_wrapper" class="header_section_wrapper">
        <div class="container">
            <div class="header-section">
                <div class="row">
                    <div class="col-md-4">
                        <div class="left_section">
                            <span class="date">
                                {% now "D" %}
                            </span>
                            <span class="time">
                                {% now "jS F Y" %}
                            </span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="logo">
                            <a href="/"><img src="{% static "img/cs.png" %}"></a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="navigation-section">
                <nav class="navbar-default">
                    <div class="container">
                        <ul class="nav navbar-nav main-nav">
                            <li class="active"><a href="/">Головна</a></li>
                            <li class="active"><a href="{% url 'advert_add' %}">Додати оголошення</a></li>
                        </ul>
                    </div>
                </nav>
            </div>

            {% block content %}
            {% endblock %}

        </div>
    </section>

    <section id="footer_section" class="footer_section">
        <div class="footer_bottom_Section">
            <div class="container">
                <div class="row">
                    <div class="footer">
                        <div class="col-sm-12">
                            <p>&copy; Всі права захищені ;)</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
  </div>

  <!-- jquery Core-->
  <script src="{% static "js/jquery-2.1.4.min.js" %}"></script>

  <!-- Bootstrap -->
  <script src="{% static "js/bootstrap.min.js" %}"></script>

  <!-- Theme Script -->
  <script src="{% static "js/script.js" %}"></script>

  <script src="{% static "js/bootstrap-table-editable.js" %}"></script>
  <script src="{% static "js/bootstrap-table-export.js" %}"></script>
  <script src="{% static "js/bootstrap-table-filter-control.js" %}"></script>
  <script src="{% static "js/bootstrap-table.js" %}"></script>
  <script src="{% static "js/tableExport.js" %}"></script>
  </body>

  </html>